- client/.eslintrc.json
- client/.prettierrc.json
- client/package-lock.json
- client/package.json
- client/tsconfig.json
- client/webpack.common.js
#2 
ESLint와 Prettier 설정
* ESlint, Prettier 추가
* 파일 일부 Lint
TSLint는 Deprecated 되어 ESlint를 사용했습니다.
Prettier도 결국 사용하게 되었읍니다...
* 안되는 부분이 있다면 바로바로 `rule`을 수정하시거나 Issue에 남겨주시면 되겠습니다.
> 프론트엔드 eslint, prettier 설정

- .gitignore
- api/app.ts
- api/package-lock.json
- api/package.json
- api/tsconfig.json
#4 
Expresss 설정
* 타입스크립트 적용
* cors 설정
* 기타 미들웨어 추가
> express 설정

- client/package.json
- client/src/lib/component/index.ts
- client/src/lib/observer/index.ts
- client/src/lib/observer/type.ts
#25 
타입스크립트로 컴포넌트 및 옵저버 패턴을 구현했다.
> [FE] 컴포넌트 프레임워크, 옵저버 패턴 구현

- client/package.json
- client/src/lib/component/index.ts
- client/src/lib/observer/index.ts
- client/src/lib/observer/type.ts
- client/src/lib/router/index.ts
- client/src/lib/router/type.ts
#26 
typeScript를 이용해서 옵저버 패턴과 함께 사용될 라우터구현
Class의 타입이 어떤 것인지 파악하지 못해서 작성하지 못했다. 
자동으로 any가 적용되는 것 같은데 이 부분을 파악해서 적용이 필요하다.
> [FE] SPA 라우터 구현

- api/.eslintrc.json
- api/.prettierrc.json
- api/package-lock.json
- api/package.json
- api/tsconfig.json
- client/.eslintrc.json
#2 
백엔드 ESLint, Prettier 적용
* 백엔드 ESLint, Prettier 적용
* 프론트엔드 ESLint 규칙 (`quotes`, `comma-dangle`) 추가
* 규칙 추가 필요시 바로 추가하면 됩니다
> 백엔드 ESLint, Prettier 적용 및 ESLint 규칙 추가

- api/app.ts
- api/utils/env.ts
#6 
백엔드에 환경변수 적용
* `utils` 폴더 추가
* `env.ts` 파일 추가
* `require`와 `import`의 로드 순서로 인해 따로 파일을 분리했습니다.
> 백엔드 환경변수 적용

- client/index.ts
- client/src/App.ts
- client/src/configs/routes.ts
- client/src/lib/component/index.ts
- client/src/lib/router/index.ts
#25 #49 
- APP 컴포넌트를 개발
- APP 컴포넌트에서 페이징 할 수 있도록 라우터를 적용시켰다.
> [FE] 라우터 적용 및 APP 컴포넌트 개발

- client/index.ts
- client/src/App.ts
- client/src/configs/routes.ts
- client/src/lib/component/index.ts
- client/src/lib/router/index.ts
- client/tsconfig.json
- client/webpack.common.js
> [FE] 절대 경로 설정 

- client/src/store/page.ts
> 라우터를 위한 page 전역 상태 추가

- client/custom.d.ts
- client/public/assets/icon/activeSubmitBtn.svg
- client/public/assets/icon/checkIcon.svg
- client/public/assets/icon/inActiveSubmitBtn.svg
- client/public/assets/icon/plusIcon.svg
- client/public/assets/icon/trashIcon.svg
- client/src/components/CategoryBadge/index.ts
- client/src/components/CategoryBadge/style.scss
- client/src/components/TransactionForm/index.ts
- client/src/components/TransactionForm/style.scss
- client/src/components/TransactionList/DayTransaction.ts
- client/src/components/TransactionList/TransactionRecord.ts
- client/src/components/TransactionList/index.ts
- client/src/components/TransactionList/style.scss
- client/src/constant/category.ts
- client/src/lib/component/index.ts
- client/src/lib/component/type.ts
- client/src/pages/MainPage/index.ts
- client/src/style/reset.scss
- client/src/type/transaction.ts
- client/src/type/type.ts
- client/src/utils/date.ts
- client/src/utils/price.ts
#9 
메인페이지 마크업 진행
- 카테고리 뱃지
- 리스트
- input form 
- 수정 부분 적용
> [FE] 메인페이지 마크업 

- client/src/components/TransactionList/DayTransaction.ts
- client/src/components/TransactionList/TransactionRecord.ts
- client/src/components/TransactionList/style.scss
- client/src/type/transaction.ts
> [FE] 메인페이지 거래내역 편집 마크업

- client/src/pages/ChartPage/drawCoordinatePlane.ts
- client/src/pages/ChartPage/drawPieChart.ts
#12 
차트 페이지 캔버스 그리기 함수 타입 수정
캔버스 그리기 함수 타입 수정
> 캔버스 그리기 함수 타입 수정

- client/src/components/Calendar/CalendarDate.ts
- client/src/components/Calendar/CalendarDay.ts
- client/src/components/Calendar/TotalPriceInfo.ts
- client/src/components/Calendar/index.ts
- client/src/components/Calendar/style.scss
- client/src/pages/CalendarPage/index.ts
- client/src/store/transaction.ts
- client/src/style/global.scss
- client/src/utils/calendar.ts
#11 
- 달력 페이지 마크업 
- 달력 목데이터 만들다가 2차원 배열로 날짜 받아오는 함수를 만들었습니다.
- 전역 상태 하나 오늘날짜 기준으로 만들었습니다.
- 오늘날짜 기준으로 색칠
> [FE] 달력 페이지 마크업

- client/public/assets/icon/activePicker.svg
- client/public/assets/icon/inActivePicker.svg
- client/public/assets/icon/picker.svg
- client/src/components/TransactionHeader/index.ts
- client/src/components/TransactionHeader/style.scss
- client/src/pages/MainPage/index.ts
- client/webpack.dev.js
> [FE] 메인페이지 마크업

- client/index.ts
- client/src/App.ts
- client/src/lib/router/index.ts
- client/src/pages/SignInPage/index.ts
- client/src/store/page.ts
#26 #10 
- 로그인에 따른 routes 설정
- 데모 로그인 버튼 생성
> [FE] 로그인에 따른 routes 설정 및 데모 로그인

- api/app.ts
- api/configs/constants.ts
- api/configs/cors.ts
- api/middlewares/validateToken.ts
- api/models/init-mock-data.ts
- api/models/schema.ts
- api/routes/auth/index.ts
- api/routes/auth/signin/index.ts
- api/routes/auth/signout/index.ts
- api/routes/auth/signup/index.ts
- api/routes/index.ts
- api/routes/payment/index.ts
- api/routes/transaction/index.ts
- api/routes/transaction/statistics/index.ts
- api/services/auth.ts
- api/tsconfig.json
- api/utils/errorGenerator.ts
- api/utils/errorHandler.ts
- api/utils/jwt.ts
#5 #51
백엔드 API 서버 기본코드 추가
* DB 스키마 적용
* API 서버 절대경로 설정
* API 서버 유틸함수 추가
* CORS 설정
* API 서버 베이스 코드 추가
* 절대경로를 설정했으니 사용하시면 됩니다.
> [API] api 기본코드 추가

- api/routes/auth/index.ts
- api/services/auth.ts
- api/utils/jwt.ts
#22
최초 로그인 시 토큰의 유효성을 검사하는 API
* 토큰 유효성 검사 API 추가
* header로 부터 token을 가져오는 유틸함수 추가
웹앱 최초 접속시에 이 API를 사용해서 로그인 여부를 판단해야합니다.
> 토큰 유효성 검사 API

- api/routes/index.ts
- api/routes/payment/index.ts
- api/services/auth.ts
- api/services/payment.ts
- api/utils/errorHandler.ts
- api/utils/jwt.ts
> [BE] 결재수단 생성 API 

- api/routes/payment/index.ts
- api/services/payment.ts
- api/utils/errorHandler.ts
> [BE] 거래수단 삭제 API

- api/routes/payment/index.ts
- api/services/payment.ts
- api/utils/jwt.ts
> [BE] 결제수단 불러오기 API

- api/routes/transaction/index.ts
- api/services/payment.ts
- api/services/transaction.ts
- api/utils/errorHandler.ts
- api/utils/jwt.ts
#15 
결제내역 추가하기 API 구현
- 결제내역 추가하기 API
- 모든 내용이 같아도 작성할 수 있게 구현했습니다.
- 다만 소유하고 있지 않은 결제수단으로 삽입 시에는 에러를 반환합니다.
> [BE] 결제내역 추가하기 API

- api/routes/transaction/index.ts
- api/services/payment.ts
- api/services/transaction.ts
- api/utils/errorHandler.ts
- api/utils/jwt.ts
#36 
거래내역 삭제하기 API
거래내역 삭제하기 API
- 본인 거래인지 확인 후 삭제 진행
- 거래내역 api에서 공통적으로 사용하는 함수가 있기 때문에 앞에 pr에 얹어서 진행하겠습니다!
> [BE] 거래내역 삭제하기 API

- api/routes/transaction/index.ts
- api/services/payment.ts
- api/services/transaction.ts
- api/utils/errorHandler.ts
- api/utils/jwt.ts
#35 
거래내역 수정하기 API
거래내역 수정하기 API
- 본인 거래 확인
- 본인 결제수단 확인
위 2가지를 확인 후 수정 진행
> [BE] 거래내역 수정하기 API

- api/routes/transaction/statistics/index.ts
- api/services/transaction.ts
- api/utils/errorHandler.ts
#78 
차트페이지에 필요한 통계 데이터 불러오기 위한 API
* 연도별 카테고리 지출 내역 트렌드
* 월별 카테고리별 지출 내역 
* 달력 페이지에서 사용될 데이터
> 차트 페이지에 필요한 통계 데이터 API

- api/routes/transaction/index.ts
- api/services/transaction.ts
- api/types/transaction.ts
- api/utils/errorHandler.ts
#14 
메인화면 거래내역 조회 API
- 거래내역 날짜별로 반환
- 수입, 지출 가격 총합 반환
거래내역 전반적인 API에 날짜 validation 추가
> [BE] 메인화면 거래내역 조회 API

- api/routes/payment/index.ts
- api/routes/transaction/index.ts
> [BE]fix유저아이디 목데이터 삭제 및 access token 적용

- client/index.ts
- client/src/App.ts
- client/src/configs/urls.ts
- client/src/lib/router/index.ts
- client/src/pages/SignInPage/index.ts
- client/src/pages/SignUpPage/index.ts
- client/src/utils/fetchWrapper.ts
#26 
웹 페이지 최초 진입시 로그인 여부를 판단하는 로직 추가
* 가장 바깥의 `index.ts`에 로그인 여부 판단 및 경로 설정
* 로그인 및 회원가입 메인페이지 이동 코드 제거
* `/` 외의 경로에서 액세스 토큰을 지우고 새로고침 할 경우 로그인 페이지로 이동하지 않는 경우 발생
> 웹앱 초기 로그인 여부 판단

- client/index.ts
- client/public/assets/icon/xBtn.svg
- client/src/App.ts
- client/src/api/payment.ts
- client/src/api/transaction.ts
- client/src/components/TransactionForm/index.ts
- client/src/components/TransactionForm/style.scss
- client/src/components/dropdown/CategoryDropdown.ts
- client/src/components/dropdown/PaymentDropdown.ts
- client/src/components/dropdown/style.scss
- client/src/configs/urls.ts
- client/src/lib/component/index.ts
- client/src/store/payment.ts
- client/src/utils/category.ts
- client/src/utils/dataSetting.ts
- client/src/utils/date.ts
#28 #32 
거래내역 생성
- 드롭다운 
- 거래내역 생성
> [FE] 거래내역 생성

- api/services/transaction.ts
#78 
결제내역 통계 받아오는 데이터 포맷 변경
* 금액 음수만 불러오기로 변경
* 13자리 배열 -> 12자리 배열로 변경
> 결제내역 통계 받아오는 데이터 포맷 변경

- client/src/api/transaction.ts
- client/src/components/TransactionForm/index.ts
- client/src/components/TransactionList/TransactionRecord.ts
- client/src/components/dropdown/style.scss
#28 
거래내역 수정, 삭제
- 거래내역 수정
- 거래내역 삭제
- 제출 버튼 조건부 렌더링
- 거래내역 가격 , 추가
> [FE] 거래내역 수정, 삭제

- client/src/components/CategoryStatistics/index.ts
- client/src/components/TransactionForm/index.ts
- client/src/pages/ChartPage/index.ts
- client/src/utils/dataSetting.ts
> [Fix][FE] api 반환값 변화에 따라서 수정

- api/services/transaction.ts
- api/utils/date.ts
- api/utils/error-handler.ts
- api/utils/handleError.ts
- client/src/components/TransactionForm/index.ts
- client/src/components/TransactionForm/style.scss
- client/src/utils/date.ts
#28  #15 #35 
거래내역 추가, 수정 에러처리
- 날짜 유효성 검사
- 카테고리 유효성 검사
- 가격 유효성 검사
> [FE,BE] 거래내역 추가, 수정 에러처리

- client/src/api/calendar.ts
- client/src/api/chart.ts
- client/src/api/index.ts
- client/src/api/payment.ts
- client/src/api/transaction.ts
- client/src/components/TransactionForm/index.ts
- client/src/components/TransactionList/TransactionRecord.ts
- client/src/components/dropdown/PaymentDropdown.ts
- client/src/components/popup/PaymentAddPopup.ts
- client/src/components/popup/style.scss
- client/src/type/type.ts
#31 
결제수단 추가,삭제 구현
- 결제수단 추가 팝업 마크업
- 결제수단 추가
- 빈 값 에러처리
- 이미 존재하는 값 에러처리
- 결제수단 삭제
- transaction form 중첩 렌더링 되는 것 수정 (setComponent를 조건부로 처리)
- api 반환타입 설정 및 분리
> [FE] 결제수단 추가,삭제 구현

- api/package-lock.json
- api/package.json
- api/routes/auth/github/index.ts
- api/routes/auth/index.ts
- api/services/auth.ts
- client/src/api/auth.ts
- client/src/pages/SignInPage/index.ts
- client/src/utils/window.ts
> 깃허브 소셜로그인 구현

- api/routes/transaction/index.ts
- api/services/transaction.ts
- api/types/transaction.ts
- client/src/api/chart.ts
- client/src/components/CategoryStatistics/drawPieChart.ts
- client/src/components/CategoryStatistics/index.ts
- client/src/components/Trend/index.ts
- client/src/pages/ChartPage/index.ts
#14 #34 #99 
차트 페이지 리팩토링
* 결제내역 불러오기 API 카테고리 쿼리 추가
* 차트페이지 연간 트렌드 결제내역 불러오기 추가
* 차트페이지 카테고리 클릭 시 트렌드 보여주기
* 지출이 없을 경우 파이차트 기본 모양 보여주기
> 차트 페이지 리팩토링

- api/configs/cors.ts
> [FIX] cors origin

- client/src/components/Calendar/style.scss
- client/src/components/CategoryStatistics/drawPieChart.ts
- client/src/components/Header/index.ts
- client/src/components/Header/style.scss
- client/src/components/TransactionForm/index.ts
- client/src/components/TransactionForm/style.scss
- client/src/components/TransactionList/DayTransaction.ts
- client/src/components/TransactionList/TransactionRecord.ts
- client/src/components/TransactionList/index.ts
- client/src/components/TransactionList/style.scss
- client/src/components/Trend/index.ts
- client/src/components/popup/style.scss
- client/src/configs/routes.ts
- client/src/pages/LoginProcessPage/index.ts
- client/src/pages/LoginProcessPage/style.scss
- client/src/pages/MainPage/index.ts
- client/src/pages/SignInPage/index.ts
- client/src/utils/dataSetting.ts
#117 
QA기반 오류 수정 및 리팩토링
[QA_ISSUE](https://github.com/woowa-techcamp-2021/cashbook-1/issues/117)
> [FIX] QA기반 오류 수정 및 리팩토링

- client/public/assets/icon/point.svg
- client/src/components/CategoryStatistics/drawPieChart.ts
- client/src/components/CategoryStatistics/index.ts
- client/src/components/Trend/drawCoordinatePlane.ts
- client/src/components/Trend/drawLineChart.ts
- client/src/components/Trend/index.ts
- client/src/pages/ChartPage/index.ts
- client/src/store/statistics.ts
#117 
UI 버그 수정 및 리팩토링
* 차트 페이지 카테고리 통계 선택시 배경 어두워지지 않는 문제 해결
* 선 그래프 곡선화 및 꼭지점 추가
* 선 그래프 곡선은 HTML canvas 베지어 곡선을 적용
* 꼭지점은 svg 이미지로 구현. `drawImage()`가 `arc()`에 비해 성능상 우위라 이미지 적용
> UI 버그 수정 및 리팩토링

- client/src/components/Header/index.ts
> [FIX] 메인 버튼 구문 위치 조정
